---
- name: passman-install
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:

    # - name: Run the equivalent of "apt-get update"
    #   apt:
    #     update_cache: yes

    # - name: Upgrade all packages to the latest version
    #   apt:
    #     name: "*"
    #     state: latest

    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - python3
          - python3-pip
          - python3-pil
          - python3-numpy
          - samba
          - samba-common-bin
          - libxslt1-dev
          - build-essential
          - acl # Ansible needs this to become an unprivileged user

    - name: Create group for the app user
      group:
        name: passman
        gid: 2000

    - name: Create user to run the app
      user:
        name: passman
        comment: Password Manager
        shell: /bin/bash
        uid: 2000
        groups: passman,adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,render,netdev,spi,i2c,gpio

    - name: Allow the passman user to shut down the device
      copy:
        dest: /etc/sudoers.d/010_passman-shutdown
        owner: root
        group: root
        mode: '0640'
        content: |
          passman ALL=(root) NOPASSWD: /usr/sbin/shutdown

    - name: Allow the passman user to manage services (polkit < 0.106 version - Raspbian has 0.105)
      # polkit 0.105 doesn't allow fine-grain JavaScript rules so we can't limit it by service name
      copy:
        dest: /etc/polkit-1/localauthority/50-local.d/50-allow-passman-daemon-ctrl.pkla
        owner: root
        group: root
        mode: '0644'
        content: |
          [Allow starting and stopping services for passman]
          Identity=unix-user:passman
          Action=org.freedesktop.systemd1.manage-units
          ResultAny=yes
          ResultInactive=yes
          ResultActive=yes

    - name: Install Python packages with pip
      become: yes
      become_user: passman
      pip:
        name: "{{ packages }}"
        executable: pip3
      vars:
        packages:
          - RPi.GPIO
          - spidev
          - pykeepass
          - smbus
          - dbus-python

    - name: Enable i2c in the boot configuration
      lineinfile:
        path: /boot/config.txt
        insertafter: "^\\[all\\]$"
        line: "{{ item.line }}"
      loop:
        - line: 'dtparam=i2c_arm=on'
        - line: 'dtparam=spi=on'
        - line: 'dtoverlay=dwc2,dr_mode=peripheral'

    - name: Enable required modules in /etc/modules
      lineinfile:
        path: /etc/modules
        line: "{{ item.line }}"
      loop:
        - line: 'i2c-dev'
        - line: 'dwc2'
        - line: 'libcomposite'

    - name: Copy script to initialise USB gadget on boot
      copy:
        src: ./assets/init_usb_gadget
        dest: /usr/bin/init_usb_gadget
        owner: root
        group: root
        mode: '0755'

    - name: Enable gadget script on boot
      lineinfile:
        path: /etc/rc.local
        insertbefore: "^exit.*$"
        line: "/usr/bin/init_usb_gadget"

    - name: Create directory for BCM2835 driver
      file:
        path: /root/bcm-driver
        state: directory
        mode: '0700'

    - name: Unzip the BCM2835 driver
      unarchive:
        src: ./assets/bcm2835-1.71.tar.gz
        dest: /root/bcm-driver

    - name: Build and install the BCM driver
      shell: |
        ./configure
        make
        make check
        make install
      args:
        executable: /bin/bash
        chdir: /root/bcm-driver/bcm2835-1.71
        creates: /usr/local/lib/libbcm2835.a

    - name: Copy WiringPi package
      copy:
        src: ./assets/wiringpi-latest.deb
        dest: /root/wiringpi-latest.deb
        owner: root
        group: root
        mode: '0600'

    - name: Install WiringPi Package
      apt:
        deb: /root/wiringpi-latest.deb

    - name: Create directory to share Keepass Database
      file:
        path: /home/passman/database
        owner: passman
        group: passman
        state: directory
        mode: '0700'

    - name: Create Samba include directory
      file:
        path: /etc/samba/smb.conf.d
        owner: root
        group: root
        state: directory
        mode: '0755'

    - name: Create Samba custom config file
      copy:
        dest: /etc/samba/smb.conf.d/passman.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          [passman]
          path = /home/passman/database
          browsable = yes
          writeable = yes
          create mask = 0700
          directory mask = 0700
          public = yes
          force user = passman

    - name: Include our custom Samba config file in the main config
      lineinfile:
        path: /etc/samba/smb.conf
        line: "include = /etc/samba/smb.conf.d/passman.conf"

    - name: Ensure that smbd is disabled by default
      systemd:
        name: smbd.service
        state: stopped
        enabled: no